routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->middleware('verified');

Route::resource('doctores', 'DoctorController');

Route::resource('clinicas', 'ClinicController');

Route::resource('recetas', 'RecipeController');

Route::name('imprimir')->get('/imprimir-pdf', 'RecipeController@store');

app/Models/Recipe.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class Recipe
 * @package App\Models
 * @version June 17, 2020, 11:41 pm UTC
 *
 * @property string $name
 * @property string $age
 * @property string $sex
 * @property string $date_recipe
 * @property string $diagnosis
 * @property string $indications
 * @property string $upcoming_appointments
 * @property string $doctor_id
 */
class Recipe extends Model
{
    use SoftDeletes;

    public $table = 'recipes';


    protected $dates = ['deleted_at'];



    public $fillable = [
        'name',
        'age',
        'sex',
        'date_recipe',
        'diagnosis',
        'indications',
        'upcoming_appointments',
        'doctor_id'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'name' => 'string',
        'age' => 'string',
        'sex' => 'string',
        'date_recipe' => 'date',
        'diagnosis' => 'string',
        'indications' => 'longText',
        'upcoming_appointments' => 'string',
        'doctor_id' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'name' => 'required',
        'age' => 'required',
        'sex' => 'required',
        'date_recipe' => 'required',
        'diagnosis' => 'required',
        'indications' => 'required',
        'doctor_id' => 'required'
    ];

    public function doctors(){
        return $this->hasOne('App\Models\Doctor');
    }


}

app/Http/Controllers/RecipeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateRecipeRequest;
use App\Http\Requests\UpdateRecipeRequest;
use App\Repositories\RecipeRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\RedirectResponse;
use Illuminate\Routing\Redirector;
use Illuminate\View\View;
use App\Models\Doctor;
use App\Models\Clinic;
use Response;

class RecipeController extends AppBaseController
{
    /** @var  RecipeRepository */
    private $recipeRepository;

    public function __construct(RecipeRepository $recipeRepo)
    {
        $this->recipeRepository = $recipeRepo;
    }

    /**
     * Display a listing of the Recipe.
     *
     * @param Request $request
     *
     * @return Response|Factory|RedirectResponse|Redirector|View
     */
    public function index(Request $request)
    {
        $doctor= Doctor::pluck('name','id');

        $recipes = $this->recipeRepository->all();

        return view('recipes.index')
            ->with('recipes', $recipes)
            ->with('doctor',$doctor);
    }

    /**
     * Show the form for creating a new Recipe.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View|Response
     */
    public function create()
    {
        $doctor= Doctor::pluck('name','id');
        //dd($doctor);
        return view('recipes.create')->with('doctor',$doctor);
    }

    /**
     * Store a newly created Recipe in storage.
     *
     * @param CreateRecipeRequest $request
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector|Response
     */
    public function store(CreateRecipeRequest $request)
    {
        $input = $request->all();
        $doctor= Doctor::find(1);
        $clinic = Clinic::find(1);
        $recipe = $this->recipeRepository->create($input);
        $pdf = \PDF::loadView('pdf',['input'=>$input,'doctor'=>$doctor]);
        $pdf->download('primerpdf.pdf');

        Flash::success('Recipe saved successfully.');
        return redirect(route('recetas.index'));
        //return $pdf->download('primerpdf.pdf');

    }

    /**
     * Display the specified Recipe.
     *
     * @param int $id
     *
     * @return Factory|RedirectResponse|Redirector|View|Response
     */
    public function show($id)
    {
        $recipe = $this->recipeRepository->find($id);

        if (empty($recipe)) {
            Flash::error('Recipe not found');

            return redirect(route('recetas.index'));
        }

        return view('recipes.show')->with('recipe', $recipe);
    }

    /**
     * Show the form for editing the specified Recipe.
     *
     * @param int $id
     *
     * @return Factory|RedirectResponse|Redirector|View|Response
     */
    public function edit($id)
    {
        $recipe = $this->recipeRepository->find($id);

        if (empty($recipe)) {
            Flash::error('Recipe not found');

            return redirect(route('recetas.index'));
        }

        return view('recipes.edit')->with('recipe', $recipe);
    }

    /**
     * Update the specified Recipe in storage.
     *
     * @param int $id
     * @param UpdateRecipeRequest $request
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector|Response
     */
    public function update($id, UpdateRecipeRequest $request)
    {
        $recipe = $this->recipeRepository->find($id);

        if (empty($recipe)) {
            Flash::error('Recipe not found');

            return redirect(route('recetas.index'));
        }

        $recipe = $this->recipeRepository->update($request->all(), $id);

        Flash::success('Recipe updated successfully.');

        return redirect(route('recetas.index'));
    }

    /**
     * Remove the specified Recipe from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector|Response
     */
    public function destroy($id)
    {
        $recipe = $this->recipeRepository->find($id);

        if (empty($recipe)) {
            Flash::error('Recipe not found');

            return redirect(route('recetas.index'));
        }

        $this->recipeRepository->delete($id);

        Flash::success('Recipe deleted successfully.');

        return redirect(route('recetas.index'));
    }
}

resources/views/recipes/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Nueva Receta
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">
            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'recetas.store']) !!}

                        @include('recipes.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/recipes/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Receta
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($recipe, ['route' => ['recetas.update', $recipe->id], 'method' => 'patch']) !!}

                        @include('recipes.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/recipes/fields.blade.php
<!-- Name Field -->
<div class="form-group col-sm-12">
    {!! Form::label('name', 'Nombre del Paciente:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<!-- Age Field -->
<div class="form-group col-sm-3">
    {!! Form::label('age', 'Edad:') !!}
    {!! Form::text('age', null, ['class' => 'form-control']) !!}
</div>

<!-- Sex Field -->
<div class="form-group col-sm-3">
    {!! Form::label('sex', 'Sexo:') !!}
    <select name="sex" class="form-control">
        <option value="MASCULINO">Masculino</option>
        <option value="FEMENINO">Femenino</option>
      </select>
</div>

<!-- Date Recipe Field -->
<div class="form-group col-sm-6">
    {!! Form::label('date_recipe', 'Fecha:') !!}
    {!! Form::date('date_recipe', null, ['class' => 'form-control','id'=>'date_recipe']) !!}
</div>



<!-- Diagnosis Field -->
<div class="form-group col-sm-6">
    {!! Form::label('diagnosis', 'Diagnostico:') !!}
    {!! Form::text('diagnosis', null, ['class' => 'form-control']) !!}
</div>

<!-- Indications Field -->


<!-- Upcoming Appointments Field -->


<!-- Doctor Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('doctor_id', 'Doctor:') !!}
    {!! Form::select('doctor_id', $doctor, ['class' => 'form-control']) !!}

</div>

    <div class="form-group col-md-12">
        {!! Form::label('indications', 'Indicaciones:') !!}
        {!! Form::textarea('indications', null, ['class' => 'form-control']) !!}
    </div>


    <div class="form-group col-sm-6">
        {!! Form::label('upcoming_appointments', 'Proxima Cita:') !!}
        {!! Form::text('upcoming_appointments', null, ['class' => 'form-control']) !!}
    </div>




<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Guardar', ['class' => 'btn btn-primary']) !!}
    <button  class="btn btn-primary" href="{{route('imprimir')}}" formtarget="_blank">Generar PDF</button>

    <a href="{{ route('recetas.index') }}" class="btn btn-default">Cancelar</a>
</div>

resources/views/recipes/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Recetas</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{{ route('recetas.create') }}">Nueva Receta</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('recipes.table')
            </div>
        </div>
        <div class="text-center">

        </div>
    </div>
@endsection

resources/views/recipes/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Receta
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('recipes.show_fields')
                    <a href="{{ route('recetas.index') }}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/recipes/show_fields.blade.php
<!-- Name Field -->
<div class="form-group">
    {!! Form::label('name', 'Nombre del Paciente:') !!}
    <p>{{ $recipe->name }}</p>
</div>

<!-- Age Field -->
<div class="form-group">
    {!! Form::label('age', 'Edad:') !!}
    <p>{{ $recipe->age }}</p>
</div>

<!-- Sex Field -->
<div class="form-group">
    {!! Form::label('sex', 'Sexo:') !!}
    <p>{{ $recipe->sex }}</p>
</div>

<!-- Date Recipe Field -->
<div class="form-group">
    {!! Form::label('date_recipe', 'Fecha:') !!}
    <p>{{ $recipe->date_recipe }}</p>
</div>

<!-- Diagnosis Field -->
<div class="form-group">
    {!! Form::label('diagnosis', 'Diagnostico:') !!}
    <p>{{ $recipe->diagnosis }}</p>
</div>

<!-- Indications Field -->
<div class="form-group">
    {!! Form::label('indications', 'Indicaciones:') !!}
    <p>{{ $recipe->indications }}</p>
</div>

<!-- Upcoming Appointments Field -->
<div class="form-group">
    {!! Form::label('upcoming_appointments', 'Proxima cita:') !!}
    <p>{{ $recipe->upcoming_appointments }}</p>
</div>

<!-- Doctor Id Field -->
<div class="form-group">
    {!! Form::label('doctor_id', 'Doctor:') !!}
    <p>{{ $recipe->doctor_id }}</p>
</div>

resources/views/recipes/table.blade.php
<div class="table-responsive">
    <table class="table" id="recipes-table">
        <thead>
            <tr>
                <th>Paciente</th>
        <th>Edad</th>
        <th>Sexo</th>
        <th>Fecha</th>
        <th>Diagnostico</th>
                <th colspan="3">Administrar</th>
            </tr>
        </thead>
        <tbody>
        @foreach($recipes as $recipe)
            <tr>
                <td>{{ $recipe->name }}</td>
            <td>{{ $recipe->age }}</td>
            <td>{{ $recipe->sex }}</td>
            <td>{{ $recipe->date_recipe }}</td>
            <td>{{ $recipe->diagnosis }}</td>
                <td>
                    {!! Form::open(['route' => ['recetas.destroy', $recipe->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('recetas.show', [$recipe->id]) }}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                        <a href="{{ route('recetas.edit', [$recipe->id]) }}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Desea eliminar la receta de: $recipe->name')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>