routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->middleware('verified');

Route::resource('doctores', 'DoctorController');

Route::resource('clinicas', 'ClinicController');

Route::resource('recetas', 'RecipeController');

Route::name('imprimir')->get('/imprimir-pdf', 'RecipeController@store');

app/Models/Clinic.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class Clinic
 * @package App\Models
 * @version June 17, 2020, 11:27 pm UTC
 *
 * @property string $name
 * @property string $schedule
 * @property string $specialty
 * @property string $celphone
 * @property string $address
 */
class Clinic extends Model
{
    use SoftDeletes;

    public $table = 'clinics';
    

    protected $dates = ['deleted_at'];



    public $fillable = [
        'name',
        'schedule',
        'specialty',
        'celphone',
        'address'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'name' => 'string',
        'schedule' => 'string',
        'specialty' => 'string',
        'celphone' => 'string',
        'address' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'name' => 'required',
        'schedule' => 'required',
        'specialty' => 'required',
        'celphone' => 'required',
        'address' => 'required'
    ];

    
}

app/Http/Controllers/ClinicController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateClinicRequest;
use App\Http\Requests\UpdateClinicRequest;
use App\Repositories\ClinicRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\RedirectResponse;
use Illuminate\Routing\Redirector;
use Illuminate\View\View;
use Response;

class ClinicController extends AppBaseController
{
    /** @var  ClinicRepository */
    private $clinicRepository;

    public function __construct(ClinicRepository $clinicRepo)
    {
        $this->clinicRepository = $clinicRepo;
    }

    /**
     * Display a listing of the Clinic.
     *
     * @param Request $request
     *
     * @return Response|Factory|RedirectResponse|Redirector|View
     */
    public function index(Request $request)
    {
        $clinics = $this->clinicRepository->all();

        return view('clinics.index')
            ->with('clinics', $clinics);
    }

    /**
     * Show the form for creating a new Clinic.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View|Response
     */
    public function create()
    {
        return view('clinics.create');
    }

    /**
     * Store a newly created Clinic in storage.
     *
     * @param CreateClinicRequest $request
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector|Response
     */
    public function store(CreateClinicRequest $request)
    {
        $input = $request->all();

        $clinic = $this->clinicRepository->create($input);

        Flash::success('Clinic saved successfully.');

        return redirect(route('clinicas.index'));
    }

    /**
     * Display the specified Clinic.
     *
     * @param int $id
     *
     * @return Factory|RedirectResponse|Redirector|View|Response
     */
    public function show($id)
    {
        $clinic = $this->clinicRepository->find($id);

        if (empty($clinic)) {
            Flash::error('Clinic not found');

            return redirect(route('clinicas.index'));
        }

        return view('clinics.show')->with('clinic', $clinic);
    }

    /**
     * Show the form for editing the specified Clinic.
     *
     * @param int $id
     *
     * @return Factory|RedirectResponse|Redirector|View|Response
     */
    public function edit($id)
    {
        $clinic = $this->clinicRepository->find($id);

        if (empty($clinic)) {
            Flash::error('Clinic not found');

            return redirect(route('clinicas.index'));
        }

        return view('clinics.edit')->with('clinic', $clinic);
    }

    /**
     * Update the specified Clinic in storage.
     *
     * @param int $id
     * @param UpdateClinicRequest $request
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector|Response
     */
    public function update($id, UpdateClinicRequest $request)
    {
        $clinic = $this->clinicRepository->find($id);

        if (empty($clinic)) {
            Flash::error('Clinic not found');

            return redirect(route('clinicas.index'));
        }

        $clinic = $this->clinicRepository->update($request->all(), $id);

        Flash::success('Clinic updated successfully.');

        return redirect(route('clinicas.index'));
    }

    /**
     * Remove the specified Clinic from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector|Response
     */
    public function destroy($id)
    {
        $clinic = $this->clinicRepository->find($id);

        if (empty($clinic)) {
            Flash::error('Clinic not found');

            return redirect(route('clinicas.index'));
        }

        $this->clinicRepository->delete($id);

        Flash::success('Clinic deleted successfully.');

        return redirect(route('clinicas.index'));
    }
}

resources/views/clinics/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Nueva Clinica
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">
            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'clinicas.store']) !!}

                        @include('clinics.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/clinics/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Clinica
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($clinic, ['route' => ['clinicas.update', $clinic->id], 'method' => 'patch']) !!}

                        @include('clinics.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/clinics/fields.blade.php
<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Nombre de la Clinica:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<!-- Schedule Field -->
<div class="form-group col-sm-6">
    {!! Form::label('schedule', 'Horario:') !!}
    {!! Form::text('schedule', null, ['class' => 'form-control']) !!}
</div>

<!-- Specialty Field -->


<!-- Celphone Field -->
<div class="form-group col-sm-6">
    {!! Form::label('celphone', 'Telefono:') !!}
    {!! Form::text('celphone', null, ['class' => 'form-control']) !!}
</div>

<!-- Address Field -->
<div class="form-group col-sm-6">
    {!! Form::label('address', 'Direccion:') !!}
    {!! Form::text('address', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group col-sm-12">
    {!! Form::label('specialty', 'Especialidades:') !!}
    {!! Form::textarea('specialty', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Guardar', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('clinicas.index') }}" class="btn btn-default">Cancelar</a>
</div>

resources/views/clinics/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Clinicas</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{{ route('clinicas.create') }}">Añadir Clinica</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('clinics.table')
            </div>
        </div>
        <div class="text-center">

        </div>
    </div>
@endsection

resources/views/clinics/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Clinic
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('clinics.show_fields')
                    <a href="{{ route('clinicas.index') }}" class="btn btn-default">Atras</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/clinics/show_fields.blade.php
<!-- Name Field -->
<div class="form-group">
    {!! Form::label('name', 'Nombre de la Clinica:') !!}
    <p>{{ $clinic->name }}</p>
</div>

<!-- Schedule Field -->
<div class="form-group">
    {!! Form::label('schedule', 'Horario:') !!}
    <p>{{ $clinic->schedule }}</p>
</div>

<!-- Specialty Field -->
<div class="form-group">
    {!! Form::label('specialty', 'Especialidades:') !!}
    <p>{{ $clinic->specialty }}</p>
</div>

<!-- Celphone Field -->
<div class="form-group">
    {!! Form::label('celphone', 'Telefono:') !!}
    <p>{{ $clinic->celphone }}</p>
</div>

<!-- Address Field -->
<div class="form-group">
    {!! Form::label('address', 'Direccion:') !!}
    <p>{{ $clinic->address }}</p>
</div>

resources/views/clinics/table.blade.php
<div class="table-responsive">
    <table class="table" id="clinics-table">
        <thead>
            <tr>
                <th>Nombre de la Clinica</th>
        <th>Horario</th>
        <th>Direccion</th>
                <th colspan="3">Administrar</th>
            </tr>
        </thead>
        <tbody>
        @foreach($clinics as $clinic)
            <tr>
                <td>{{ $clinic->name }}</td>
            <td>{{ $clinic->schedule }}</td>
            <td>{{ $clinic->address }}</td>
                <td>
                    {!! Form::open(['route' => ['clinicas.destroy', $clinic->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('clinicas.show', [$clinic->id]) }}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                        <a href="{{ route('clinicas.edit', [$clinic->id]) }}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Desea eliminar la clinica: $clinic->name')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>